"""add_country_code_to_contact_details

Revision ID: 1629b76a665a
Revises: c3d4e5f6a7b8
Create Date: 2026-04-26 09:55:39.460813

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1629b76a665a'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_card_sync_history_card_id', table_name='card_sync_history')
    op.add_column('contact_details', sa.Column('country_code', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_details', 'country_code')
    op.create_index('ix_card_sync_history_card_id', 'card_sync_history', ['card_id'], unique=False)
    # ### end Alembic commands ###
